# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"/\n\x08\x64\x61tapred\x12\x0f\n\x07percent\x18\x01 \x01(\x02\x12\x12\n\ndataresult\x18\x02 \x01(\t\"\x19\n\timg_path2\x12\x0c\n\x04path2\x18\x01 \x01(\t2-\n\tInference\x12 \n\x07predict\x12\n.img_path2\x1a\t.datapredb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAPRED._serialized_start=19
  _DATAPRED._serialized_end=66
  _IMG_PATH2._serialized_start=68
  _IMG_PATH2._serialized_end=93
  _INFERENCE._serialized_start=95
  _INFERENCE._serialized_end=140
# @@protoc_insertion_point(module_scope)
